### PR TITLE
(#35) - Add blog section

### PR DESCRIPTION
**Pull request by natoverse**
* Adds link to main blog page in footer
* Migrates the existing tech blog content

@bingles @Luckyshot101 this is my first cut at getting the tech blog moved over. Needs to be made pretty and to confirm a final location for the link ("Blog" under "Connect" in footer right now).

### CODE REVIEW

**Comment by Ken-2scientists** [comment]
There's a couple of cosmetic things I'd like to see us address before merging this in:

* I'd like to see the author listed on the blog list page (currently on each post, but not in the main list at /blog)
* The blog listing needs a hero image for the background behind the intro text
* It seems that we probably won't commit to finding an image to insert in every blog post, so we probably ought to change the post layout to eliminate the large header area and just leap into the text (preserving the nav of course)
* I'd rather have the full text of the post present rather than read a couple paragraphs and then bounce out to another site. Perhaps the Post layout can have an "Originally posted on X" link at the top under the date and byline.

**Comment by Ken-2scientists** [comment]
Also, I think that 'Blog' belongs in the top-level nav as its own item. I'd probably place the link between Careers and Contact. I'd also probably place it under 'About' in the footer rather than under 'Connect'

**Comment by natoverse** [comment]
Latest commits address most of @Ken-2scientists comments.

I copied the CSS block for 'contact' to the blog listing page so it would at least have a hero image. @bingles do you have any additional unused images that would be appropriate instead?

The only major outstanding hurdle I found was that I couldn't remove the hero content block entirely from the individual blog posts, because the header animation depends on having some amount of content to slide under it. My suggestion is to leave it 'short' (right now, I have it at 180px, which is 3x the nav so it slides smoothly) and put in a generic hero image 'strip' that is the same for all blog posts.

I have not yet copied more of the content from the original sources. I'll experiment with that soon.

**Comment by bingles** [comment]
@natoverse Sure thing! I'll find a hero image and add a generic image to support the individual blog post layout. Any opposition to some layout tweaking and cleanup?

**Comment by bingles** [comment]
@Ken-2scientists and @natoverse I've committed some styling tweaks to the blog sections for your review. Thanks!

**Comment by natoverse** [comment]
This looks great @bingles!

The only reservation I have is the removal of the "read more" links. I agree it looks cleaner without them, but was worried that the headers didn't look like links since they match the rest of the site headers. Would it help to make, say, the pub date look more like a link? I just want to make sure it is clear there is more to see and how to get there. What do you guys think?

**Comment by natoverse** [comment]
@Ken-2scientists these latest commits copy the entire content of my post to the blog as an experiment. It was a bit painful getting it from Medium, as all the links need to be tracked down and reformatted with Markdown. I did not have any images, so did not test the effort there.

I set up the post format so either partial or full posts can be published. For all posts, the header gets a 'Published on <...>' link. If they omit a `preview` YAML flag, that header link is the only link to the original. If they add that flag, it is known that they only copied some of the content, so a 'Read the rest on <...>' link appears at the bottom.

This way, authors can choose to copy all of the content or not, based on their preference for the workload to cross-publish and whether they want to make sure they get a view registered on the source platform. We can encourage staff to put the entire content there so users don't have to leave the site, but also leave them the option.

**Comment by bingles** [comment]
@natoverse I'm glad you mentioned that, because I was worried it might not be that intuitive, but preferred the cleaner look. I like the idea of adding a link to the pub date and made the tweak...thoughts?

**Comment by natoverse** [comment]
Yeah, I think that is pretty good.

**Comment by Ken-2scientists** [comment]
@natoverse I'm seeing the same issues on a local build of the site that you and I were looking at on `stage` yesterday: each post is just getting generated as an HTML fragment with no formatting or metadata. Could one of the commits for #35 broken that somehow?

**Comment by natoverse** [comment]
@Ken-2scientists looks good now. It appears that the version of Jekyll we have in prod doesn't support the 'defaults' block in _config.yml, so the post generation was missing the `layout: post` property that told it which template to use. Looks like this may be the reference: https://github.com/jekyll/jekyll/pull/2774

**Comment by natoverse** [comment]
Closing since we are moving forward with Medium.

**Pull request closed without merging**
